### ISSUE TITLE
Link documentation to release

### ISSUE THREAD

**Issue by ivancrneto** [ivancrneto/pymox_#12]
Right now the docs are always being built with version 0.1

**Comment by bcatubig** [comment]
Hi @ivancrneto,

I am interested in helping with this issue. Do you have a CI system that builds and publishes releases?

**Comment by ivancrneto** [comment]
hey @bcatubig I think we need a version bump script that will do something like that: https://github.com/cobrateam/splinter/commit/85f0e33a9dea2961b1381bd4e91e3cb0584d9e18

We use CircleCI to build the project and ReadTheDocs to build the documentation
